createSession.py -s H130   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-130_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-130_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s H140   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-140_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-140_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s H140   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-140_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-140_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s H150   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-150_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-150_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s H160   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-160_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-160_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s H170   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-170_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-170_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s H180   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-180_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-180_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s H190   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-190_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-190_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s H200   -g higgs:hww      -l GluGluToHToWWTo2L2Nu_M-200_7TeV-powheg-pythia6 -i ${HOME}/HWW/input/GluGluToHToWWTo2L2Nu_M-200_7TeV-powheg-pythia6.T3_CH_PSI.dcap -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh

createSession.py -s DYEE10 -g background:hww -l DYToEE_M-10To20_TuneZ2_7TeV-pythia6            -i ${HOME}/HWW/input/DYToEE_M-10To20_TuneZ2_7TeV-pythia6.T3_CH_PSI.dcap            -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh 
createSession.py -s DYEE20 -g background:hww -l DYToEE_M-20_TuneZ2_7TeV-pythia6                -i ${HOME}/HWW/input/DYToEE_M-20_TuneZ2_7TeV-pythia6.T3_CH_PSI.dcap                -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s DYuu10 -g background:hww -l DYToMuMu_M-10To20_TuneZ2_7TeV-pythia6          -i ${HOME}/HWW/input/DYToMuMu_M-10To20_TuneZ2_7TeV-pythia6.T3_CH_PSI.dcap          -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s DYuu20 -g background:hww -l DYToMuMu_M-20_TuneZ2_7TeV-pythia6              -i ${HOME}/HWW/input/DYToMuMu_M-20_TuneZ2_7TeV-pythia6.T3_CH_PSI.dcap              -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s TT     -g background:hww -l TTTo2L2Nu2B_7TeV-powheg-pythia6                -i ${HOME}/HWW/input/TTTo2L2Nu2B_7TeV-powheg-pythia6.T3_CH_PSI.dcap                -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s W2ENu  -g background:hww -l WToENu_TuneZ2_7TeV-pythia6                     -i ${HOME}/HWW/input/WToENu_TuneZ2_7TeV-pythia6.T3_CH_PSI.dcap                     -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s W2MuNu -g background:hww -l WToENMu_TuneZ2_7TeV-pythia6                    -i ${HOME}/HWW/input/WToMuNu_TuneZ2_7TeV-pythia6.T3_CH_PSI.dcap                    -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s WW     -g background:hww -l WWTo2L2Nu_TuneZ2_7TeV-pythia6                  -i ${HOME}/HWW/input/WWTo2L2Nu_TuneZ2_7TeV-pythia6.T3_CH_PSI.dcap                  -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s WZ     -g background:hww -l WZtoAnything_TuneZ2_7TeV-pythia6-tauola        -i ${HOME}/HWW/input/WZtoAnything_TuneZ2_7TeV-pythia6-tauola.T3_CH_PSI.dcap        -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh
createSession.py -s ZZ     -g background:hww -l ZZtoAnything_TuneZ2_7TeV-pythia6-tauola        -i ${HOME}/HWW/input/ZZtoAnything_TuneZ2_7TeV-pythia6-tauola.T3_CH_PSI.dcap        -o ${HOME}/HWW/output/ -w ${HOME}/HWW/HWWAnalysis/ -t analyze/Analysis -j 20 ${HOME}/HWW/HWWAnalysis/config/selectHWW_tmpl.sh


