/********************************************************************
* tmp/G___HWWDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error tmp/G___HWWDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG___HWWDict();
extern void G__cpp_setup_inheritanceG___HWWDict();
extern void G__cpp_setup_typetableG___HWWDict();
extern void G__cpp_setup_memvarG___HWWDict();
extern void G__cpp_setup_globalG___HWWDict();
extern void G__cpp_setup_memfuncG___HWWDict();
extern void G__cpp_setup_funcG___HWWDict();
extern void G__set_cpp_environmentG___HWWDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/HWWNtuple.h"
#include "include/HWWEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G___HWWDictLN_TClass;
extern G__linked_taginfo G__G___HWWDictLN_TBuffer;
extern G__linked_taginfo G__G___HWWDictLN_TMemberInspector;
extern G__linked_taginfo G__G___HWWDictLN_TObject;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G___HWWDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G___HWWDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G___HWWDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G___HWWDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G___HWWDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G___HWWDictLN_TLorentzVector;
extern G__linked_taginfo G__G___HWWDictLN_HWWNtuple;
extern G__linked_taginfo G__G___HWWDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G___HWWDictLN_HWWElectron;
extern G__linked_taginfo G__G___HWWDictLN_HWWMuon;
extern G__linked_taginfo G__G___HWWDictLN_HWWJet;
extern G__linked_taginfo G__G___HWWDictLN_HWWPFJet;
extern G__linked_taginfo G__G___HWWDictLN_HWWEvent;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEHWWElectroncOallocatorlEHWWElectrongRsPgR;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEHWWElectroncOallocatorlEHWWElectrongRsPgRcLcLiterator;
extern G__linked_taginfo G__G___HWWDictLN_reverse_iteratorlEvectorlEHWWElectroncOallocatorlEHWWElectrongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEHWWMuoncOallocatorlEHWWMuongRsPgR;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEHWWMuoncOallocatorlEHWWMuongRsPgRcLcLiterator;
extern G__linked_taginfo G__G___HWWDictLN_reverse_iteratorlEvectorlEHWWMuoncOallocatorlEHWWMuongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEHWWJetcOallocatorlEHWWJetgRsPgR;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEHWWJetcOallocatorlEHWWJetgRsPgRcLcLiterator;
extern G__linked_taginfo G__G___HWWDictLN_reverse_iteratorlEvectorlEHWWJetcOallocatorlEHWWJetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEHWWPFJetcOallocatorlEHWWPFJetgRsPgR;
extern G__linked_taginfo G__G___HWWDictLN_vectorlEHWWPFJetcOallocatorlEHWWPFJetgRsPgRcLcLiterator;
extern G__linked_taginfo G__G___HWWDictLN_reverse_iteratorlEvectorlEHWWPFJetcOallocatorlEHWWPFJetgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<HWWElectron,allocator<HWWElectron> > G__vectorlEHWWElectroncOallocatorlEHWWElectrongRsPgR;
typedef vector<HWWMuon,allocator<HWWMuon> > G__vectorlEHWWMuoncOallocatorlEHWWMuongRsPgR;
typedef vector<HWWJet,allocator<HWWJet> > G__vectorlEHWWJetcOallocatorlEHWWJetgRsPgR;
typedef vector<HWWPFJet,allocator<HWWPFJet> > G__vectorlEHWWPFJetcOallocatorlEHWWPFJetgRsPgR;
